# Generated by Django 3.0.4 on 2020-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
