# Generated by Django 3.0.6 on 2020-05-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_blog', '0004_auto_20200509_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
