# Generated by Django 3.0.6 on 2020-05-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_blog', '0005_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': '-date_created'},
        ),
    ]
