# Generated by Django 3.0.6 on 2020-05-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_blog', '0006_auto_20200516_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
    ]
